//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiQuanCOFFEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public BAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MaBan { get; set; }
        public string TenBan { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
