//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiQuanCOFFEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public HANGHOA()
        {
            this.CHITIETHANGHOAs = new HashSet<CHITIETHANGHOA>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string LoaiHH { get; set; }
    
        public virtual ICollection<CHITIETHANGHOA> CHITIETHANGHOAs { get; set; }
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
    }
}
