//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiQuanCOFFEE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.CHITIETHANGHOAs = new HashSet<CHITIETHANGHOA>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> Sdt { get; set; }
        public string E_Mail { get; set; }
    
        public virtual ICollection<CHITIETHANGHOA> CHITIETHANGHOAs { get; set; }
    }
}
